### PR TITLE
(Issue #30) Show Error if there was a fetch error

### LINKED ISSUE #30: Display the state of of fetchData in the result list
**Need work on an existing feature? **
(a) Describe the outcome needed/goal of the feature.
At the moment, we display "Loading ..." as long as markers == null. It would be great if instead we linked the message we display to the state of the fetchData request. We should display "Loading ..." wile waiting for a response, the results if we get them, or an error message if fetchData failed.

(b) What do we need to code next?
Probably create a fetchDataState and message variables in Results and pass them as props to resultsList.
Any new messages we display need to be translated - you can add them [here](https://docs.google.com/spreadsheets/d/17vQZZnKqq4IKXUDjHOsCCLYo0KTxUDsREE7b2Ev4Ang/edit#gid=0).

@llwu - I've tentatively assigned this to you since your previous PR touched upon this feature.

### PR DESCRIPTION
**Pull request by llllvvuu**
#30

### CODE REVIEW

File: covid-19-support/src/components/Results.vue [hunk 1]
```diff
@@ -74,10 +78,13 @@ export default {
     async fetchData(query) {
       try {
         // console.log(cartoBaseURL + '&q=' + query)
+        this.fetchDataState = StatusEnum.loading
         const res = await fetch(cartoBaseURL + '&q=' + query)
```
Comment (mfincker) [inline covid-19-support/src/components/Results.vue:121]: fetch doesn't actually raise an error on a failed request. We have to manually raise an error.

We could do:
```
    const res = await fetch(cartoBaseURL + '&q=' + query)
    this.handle Errors(res)
```
And define handleErrors as:
```
    handleErrors(response) {
        if (!response.ok) {
            throw Error(response.statusText)
        }
    }
```

**Review by mfincker — DISMISSED** [review]

**Review by mfincker — APPROVED** [review]
